language: node_js
node_js:
  - "12"
script:
  - node --require ts-node/register ./utils/run_examples.ts
  - npm run test:cov
  - npm run test:perf
branches:
  only:
  - master
git:
  submodules: false
